---
language: python
services: docker

env:
  global:
    - ROLE_NAME: openwisp2
  matrix:
    #- MOLECULE_DISTRO: centos7
    - MOLECULE_DISTRO: ubuntu1604
      MOLECULE_DOCKER_COMMAND: /sbin/init
    - MOLECULE_DISTRO: ubuntu1804
    - MOLECULE_DISTRO: debian9
    - MOLECULE_DISTRO: debian10
    - MOLECULE_DISTRO: ubuntu1604
      MOLECULE_PLAYBOOK: playbook-networktopology.yml
    - MOLECULE_DISTRO: ubuntu1804
      MOLECULE_PLAYBOOK: playbook-networktopology.yml
    - MOLECULE_DISTRO: debian9
      MOLECULE_PLAYBOOK: playbook-networktopology.yml
    - MOLECULE_DISTRO: debian10
      MOLECULE_PLAYBOOK: playbook-networktopology.yml

install:
  # Install test dependencies.
  - pip install molecule docker

before_script:
  # Use actual Ansible Galaxy role name for the project directory.
  - cd ../
  - mv ansible-$ROLE_NAME openwisp.$ROLE_NAME
  - cd openwisp.$ROLE_NAME

script:
  # Run tests.
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
