---

- name: Enable firewalld
  service:
    name: firewalld
    state: started
    enabled: yes

- name: Configure firewall
  firewalld:
    permanent: true
    immediate: true
    service: "{{ item }}"
    state: enabled
  with_items:
    - http
    - https
