### openwisp2
## handlers
---

- name: reload systemd
  systemd: daemon_reload=yes
  when: ansible_distribution_release in ['xenial', 'bionic']

- name: reload supervisor
  command: supervisorctl reload

- name: restart nginx
  service: name=nginx state=restarted

- name: start redis
  service: name=redis state=started
